### ISSUE TITLE
Battery

### ISSUE THREAD

**Issue by ro85ac** [jackyes/GrowSensor#1]
On this post https://github.com/Xinyuan-LilyGO/TTGO-HiGrow/issues/3 you said that your battery works for 1 month+. Can you tell me if you use the original battery of the sensor or you made an upgrade?

**Comment by jackyes** [comment]
No originale battery, I have purchased a cheap 18650 battery + 1 battery holder on AliExpress.
The battery i choose was labelled as "9900 mah" but it's chemically impossible for that kind of battery reach that value. :)

If you want to increase the battery durarion you can set the script to upload data every 1h...beetween each upload the board Will go in dee sleep mode with a very low Power consumption

**Comment by ro85ac** [comment]
> No originale battery, I have purchased a cheap 18650 battery + 1 battery holder on AliExpress.
> The battery i choose was labelled as "9900 mah" but it's chemically impossible for that kind of battery reach that value. :)
> 
> If you want to increase the battery durarion you can set the script to upload data every 1h...beetween each upload the board Will go in dee sleep mode with a very low Power consumption

But does the 18650 battery + 1 battery holder fit into the Higrow case?

**Comment by jackyes** [comment]
i don't own the original higrow case, just uded tape ;)

**Comment by ro85ac** [comment]
@jackyes can you attach a picture ?
